### ISSUE TITLE
What's the function of boxlib.c

### ISSUE THREAD

**Issue by mxmxlwlw** [ex4sperans/SSD#1]
Hi,
     This is not a issue, but I don't know how to contact with you. So... 
     I'm now reading your code. And I want to know what is the function of file boxlib.c . Why not use python to implement it.  
                                                                                                                            Thank you!

**Comment by ex4sperans** [comment]
Hi! Thank you for your question.

This repo is currently under development as I have not finished all planned numerical experiments yet. I plan to finish preliminary version and add all the descriptions during this week, so you can follow me be aware of any updates.

Regarding your question, boxlib is a Cython module (http://docs.cython.org). I decided to wrote some of the functions in Cython instead of regular Python for efficiency. For instance, *jaccard_overlap* function gets 5x
faster being implemented in  Cython.

Best wishes.

**Comment by mxmxlwlw** [comment]
Thank you for you reply! Now I close this issue.
